name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository 🛒
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup mise ⚙️
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Install dependencies 🔧
        # include devDependencies https://stackoverflow.com/a/64648870
        run: npm ci --audit=false --include=dev --include=optional --include=peer

      - name: Build package 🏗️
        run: npm run build
